-- MySQL Script generated by MySQL Workbench
-- 07/17/16 16:07:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema spaceman
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `spaceman` ;

-- -----------------------------------------------------
-- Schema spaceman
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spaceman` DEFAULT CHARACTER SET utf8 ;
USE `spaceman` ;

-- -----------------------------------------------------
-- Table `spaceman`.`login_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spaceman`.`login_user` ;

CREATE TABLE IF NOT EXISTS `spaceman`.`login_user` (
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `username_UNIQUE` ON `spaceman`.`login_user` (`username` ASC);


-- -----------------------------------------------------
-- Table `spaceman`.`scores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spaceman`.`scores` ;

CREATE TABLE IF NOT EXISTS `spaceman`.`scores` (
  `id_scores` INT NOT NULL AUTO_INCREMENT,
  `login_user_username` VARCHAR(20) NOT NULL,
  `score` INT NOT NULL,
  `perc_enemyKilled` FLOAT NOT NULL,
  `punteria` FLOAT NOT NULL,
  `rondas` INT NOT NULL,
  PRIMARY KEY (`id_scores`, `login_user_username`),
  CONSTRAINT `fk_scores_login_user`
    FOREIGN KEY (`login_user_username`)
    REFERENCES `spaceman`.`login_user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_scores_login_user_idx` ON `spaceman`.`scores` (`login_user_username` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
